### ISSUE TITLE
大佬给看看这是咋回事

### ISSUE THREAD

**Issue by xiaoyannb** [wdvipa/mtsign#1]
已设置不显示账号密码等信息
第1个用户开始签到
登录成功
签到成功
签到详情：['![CDATA[已签到]]>']
Traceback (most recent call last):
  File "mt.py", line 252, in <module>
    run.main()
  File "mt.py", line 233, in main
    msgs = msgs + self.sign(msgs)
  File "mt.py", line 136, in sign
    lx = re.findall('value="(.*?)"',str(lxb))[0]
IndexError: list index out of range

**Comment by xiaoyannb** [comment]
pushplus推送消息变量是什么大佬，是mt_push还是dxx_push还是mt push

**Comment by wdvipa** [comment]
上面东西是已经签到过了，我改好了mt_push

**Comment by wdvipa** [comment]
> 已设置不显示账号密码等信息 第1个用户开始签到 登录成功 签到成功 签到详情：['![CDATA[已签到]]>'] Traceback (most recent call last): File "mt.py", line 252, in run.main() File "mt.py", line 233, in main msgs = msgs + self.sign(msgs) File "mt.py", line 136, in sign lx = re.findall('value="(.*?)"',str(lxb))[0] IndexError: list index out of range

已解决，使用最新版本即可
